// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP2sTTvLYi-xFGQ4hEZBBwklSirVTekHQ',
    appId: '1:1067144611048:web:83d9f6dc5c334b8826b55d',
    messagingSenderId: '1067144611048',
    projectId: 'logo-commerce',
    authDomain: 'logo-commerce.firebaseapp.com',
    storageBucket: 'logo-commerce.appspot.com',
    measurementId: 'G-TWG6SD7M62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKIQHci_D7wKkOkYwETnPcKrN3tBP00fo',
    appId: '1:1067144611048:android:76c9f8cbd5430e9d26b55d',
    messagingSenderId: '1067144611048',
    projectId: 'logo-commerce',
    storageBucket: 'logo-commerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcGb-4gD2uY9RheBWP_Zo9YoDajyIQW68',
    appId: '1:1067144611048:ios:168f2d0fd5591f4026b55d',
    messagingSenderId: '1067144611048',
    projectId: 'logo-commerce',
    storageBucket: 'logo-commerce.appspot.com',
    iosClientId: '1067144611048-ra3bd6d6p8r4pj16e1rtskb6c9vmam0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.logoCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcGb-4gD2uY9RheBWP_Zo9YoDajyIQW68',
    appId: '1:1067144611048:ios:834de848ef7be3c726b55d',
    messagingSenderId: '1067144611048',
    projectId: 'logo-commerce',
    storageBucket: 'logo-commerce.appspot.com',
    iosClientId: '1067144611048-7f4f969636ssc8guhj5nflbq7dscul9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.logoCommerce.RunnerTests',
  );
}
